//! ReviveAI domain model, Rust side.
//!
//! Every type here is the serde counterpart of a type in `src/domain/types.ts`.
//! The wire format is what the React app already expects: `camelCase` fields,
//! `snake_case` enum values, money as an integer count of paise, and timestamps
//! as ISO-8601 UTC strings.
//!
//! Taxonomy enums are generated by [`str_enum!`], which derives the serde name,
//! the SQLite representation and `Display` from a single string literal. That is
//! deliberate: a hand-written `to_sql` is exactly the kind of code that drifts
//! from its JSON name, and a drifted enum value silently disappears from a
//! filtered query instead of failing loudly.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::error::EngineError;

/// Defines a string-valued taxonomy enum with one source of truth per variant.
///
/// Generates `Serialize`/`Deserialize` (the JSON contract), `ToSql`/`FromSql`
/// (the storage contract), `Display`, `FromStr` and an `ALL` slice.
macro_rules! str_enum {
    (
        $(#[$meta:meta])*
        $name:ident { $( $variant:ident => $text:literal ),+ $(,)? }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
        pub enum $name {
            $( #[serde(rename = $text)] $variant ),+
        }

        impl $name {
            /// Every variant, in declaration order.
            pub const ALL: &'static [$name] = &[ $( $name::$variant ),+ ];

            pub const fn as_str(&self) -> &'static str {
                match self { $( $name::$variant => $text ),+ }
            }
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(self.as_str())
            }
        }

        impl std::str::FromStr for $name {
            type Err = EngineError;

            fn from_str(value: &str) -> Result<Self, Self::Err> {
                match value {
                    $( $text => Ok($name::$variant), )+
                    other => Err(EngineError::Corrupt {
                        id: stringify!($name).to_string(),
                        detail: format!("unknown value `{other}`"),
                    }),
                }
            }
        }

        impl rusqlite::types::ToSql for $name {
            fn to_sql(&self) -> rusqlite::Result<rusqlite::types::ToSqlOutput<'_>> {
                Ok(rusqlite::types::ToSqlOutput::from(self.as_str()))
            }
        }

        impl rusqlite::types::FromSql for $name {
            fn column_result(
                value: rusqlite::types::ValueRef<'_>,
            ) -> rusqlite::types::FromSqlResult<Self> {
                let text = value.as_str()?;
                text.parse::<$name>()
                    .map_err(|cause| rusqlite::types::FromSqlError::Other(Box::new(cause)))
            }
        }
    };
}

str_enum! {
    /// Normalised failure taxonomy. Razorpay's own error codes are mapped onto
    /// these on ingest, so the rules engine never has to reason about gateway
    /// vocabulary and a new code cannot silently create a new behaviour.
    FailureReason {
        InsufficientFunds => "insufficient_funds",
        CardExpired => "card_expired",
        InvalidCard => "invalid_card",
        DoNotHonour => "do_not_honour",
        AuthenticationTimeout => "authentication_timeout",
        BankDowntime => "bank_downtime",
        UpiCollectExpired => "upi_collect_expired",
        MandateRevoked => "mandate_revoked",
        LimitExceeded => "limit_exceeded",
        GatewayTimeout => "gateway_timeout",
    }
}

str_enum! {
    PaymentMethod {
        Card => "card",
        Upi => "upi",
        Netbanking => "netbanking",
        Wallet => "wallet",
        Emandate => "emandate",
        Emi => "emi",
    }
}

str_enum! {
    RecoveryStatus {
        Queued => "queued",
        Scheduled => "scheduled",
        InProgress => "in_progress",
        AwaitingCustomer => "awaiting_customer",
        Recovered => "recovered",
        Failed => "failed",
        WrittenOff => "written_off",
        Suppressed => "suppressed",
    }
}

impl RecoveryStatus {
    /// Statuses the engine still has work to do on. Drives `activeJobs` and the
    /// queue depth reported by [`crate::domain::EngineStatus`].
    pub const ACTIVE: &'static [RecoveryStatus] = &[
        RecoveryStatus::Queued,
        RecoveryStatus::Scheduled,
        RecoveryStatus::InProgress,
        RecoveryStatus::AwaitingCustomer,
    ];

    /// No further action will be taken, whatever the outcome was.
    pub const fn is_closed(&self) -> bool {
        matches!(
            self,
            RecoveryStatus::Recovered
                | RecoveryStatus::Failed
                | RecoveryStatus::WrittenOff
                | RecoveryStatus::Suppressed
        )
    }

    /// Where this status sits in the dashboard funnel.
    pub const fn funnel_stage(&self) -> FunnelStage {
        match self {
            RecoveryStatus::Recovered => FunnelStage::Recovered,
            RecoveryStatus::Scheduled | RecoveryStatus::InProgress => FunnelStage::InFlight,
            RecoveryStatus::AwaitingCustomer => FunnelStage::AwaitingCustomer,
            RecoveryStatus::Queued | RecoveryStatus::Failed | RecoveryStatus::Suppressed => {
                FunnelStage::AtRisk
            }
            RecoveryStatus::WrittenOff => FunnelStage::WrittenOff,
        }
    }
}

str_enum! {
    /// What the engine can do about a failure. One step of a playbook.
    RecoveryActionKind {
        AutoRetry => "auto_retry",
        RetryOnPayday => "retry_on_payday",
        RetryAfterDowntime => "retry_after_downtime",
        SwitchToUpi => "switch_to_upi",
        RequestCardUpdate => "request_card_update",
        SendPaymentLink => "send_payment_link",
        DunningEmail => "dunning_email",
        DunningWhatsapp => "dunning_whatsapp",
        HumanReview => "human_review",
    }
}

str_enum! {
    RiskTier {
        Critical => "critical",
        High => "high",
        Medium => "medium",
        Low => "low",
    }
}

str_enum! {
    AttemptOutcome {
        Succeeded => "succeeded",
        Failed => "failed",
        Pending => "pending",
        Skipped => "skipped",
        Delivered => "delivered",
    }
}

str_enum! {
    Channel {
        Gateway => "gateway",
        Email => "email",
        Whatsapp => "whatsapp",
        Sms => "sms",
        InApp => "in_app",
    }
}

str_enum! {
    FunnelStage {
        Recovered => "recovered",
        InFlight => "in_flight",
        AwaitingCustomer => "awaiting_customer",
        AtRisk => "at_risk",
        WrittenOff => "written_off",
    }
}

str_enum! {
    InsightKind {
        Opportunity => "opportunity",
        Risk => "risk",
        Anomaly => "anomaly",
    }
}

str_enum! {
    ActorType {
        Engine => "engine",
        User => "user",
        Webhook => "webhook",
        System => "system",
    }
}

str_enum! {
    AuditSeverity {
        Info => "info",
        Notice => "notice",
        Warning => "warning",
        Critical => "critical",
    }
}

str_enum! {
    MerchantMode {
        Test => "test",
        Live => "live",
    }
}

str_enum! {
    /// Label for whatever is currently backing the UI. The sidebar shows this
    /// verbatim so a reviewer can never mistake seeded data for engine output.
    EngineSource {
        RustEngine => "rust-engine",
        DevSeed => "dev-seed",
    }
}

str_enum! {
    /// Queue ordering. Sorting lives in the data layer so that paging stays
    /// correct: page three of an unsorted result set is meaningless.
    JobSort {
        Recent => "recent",
        AmountDesc => "amount_desc",
        ScoreDesc => "score_desc",
        SlaSoonest => "sla_soonest",
    }
}

impl JobSort {
    /// The `ORDER BY` fragment for this sort. Never interpolates user input.
    pub const fn order_by(&self) -> &'static str {
        match self {
            JobSort::Recent => "p.failed_at DESC, j.id DESC",
            JobSort::AmountDesc => "p.amount_paise DESC, j.id DESC",
            JobSort::ScoreDesc => "j.recovery_score DESC, j.id DESC",
            JobSort::SlaSoonest => "j.sla_expires_at ASC, j.id DESC",
        }
    }
}

impl Default for JobSort {
    fn default() -> Self {
        JobSort::Recent
    }
}

// ---------------------------------------------------------------------------
// Records
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomerRef {
    pub id: String,
    pub name: String,
    pub email: String,
    /// Masked at the source. The app never holds a full contact number.
    pub phone_masked: String,
    pub lifetime_value_paise: i64,
    pub successful_payments: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FailedPayment {
    pub id: String,
    pub razorpay_payment_id: String,
    pub razorpay_order_id: String,
    pub customer: CustomerRef,
    pub amount_paise: i64,
    pub method: PaymentMethod,
    pub card_network: Option<String>,
    pub issuer: Option<String>,
    pub failure_reason: FailureReason,
    /// Verbatim gateway description, shown to humans for ground truth.
    pub gateway_description: String,
    pub failed_at: String,
    pub attempt_count: i64,
    pub is_subscription: bool,
}

/// One weighted input to a score, surfaced verbatim in the UI.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    pub label: String,
    /// Contribution to the score, -1..1. Negative signals lower it.
    pub weight: f64,
    pub detail: String,
}

impl Signal {
    pub fn new(label: impl Into<String>, weight: f64, detail: impl Into<String>) -> Self {
        Signal {
            label: label.into(),
            weight,
            detail: detail.into(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecoveryAction {
    pub kind: RecoveryActionKind,
    /// Imperative and user-facing: "Retry on 1 Sep", not "RETRY_SCHEDULED".
    pub label: String,
    pub channel: Channel,
    pub confidence: f64,
    /// Why the engine chose this. Never empty.
    pub signals: Vec<Signal>,
    pub delay_minutes: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecoveryAttempt {
    pub id: String,
    pub sequence: i64,
    pub kind: RecoveryActionKind,
    pub channel: Channel,
    pub occurred_at: String,
    pub outcome: AttemptOutcome,
    /// Gateway or provider response, kept for the audit trail.
    pub note: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecoveryJob {
    pub id: String,
    pub payment: FailedPayment,
    pub status: RecoveryStatus,
    pub risk_tier: RiskTier,
    pub recovery_score: f64,
    pub recommended_action: RecoveryAction,
    pub attempts: Vec<RecoveryAttempt>,
    pub next_action_at: Option<String>,
    pub recovered_amount_paise: Option<i64>,
    /// Recovery windows close: mandates lapse, carts go cold.
    pub sla_expires_at: String,
    pub created_at: String,
    pub updated_at: String,
    /// Set when a human overrode the engine, so the UI can say so.
    pub assigned_to: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FunnelSegment {
    pub stage: FunnelStage,
    pub amount_paise: i64,
    pub job_count: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecoveryFunnel {
    pub total_paise: i64,
    pub segments: Vec<FunnelSegment>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MetricDelta {
    /// Fractional change against the previous equivalent window.
    pub change: f64,
    /// Whether an increase is good news for this metric.
    pub higher_is_better: bool,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MetricDeltas {
    pub revenue_at_risk: MetricDelta,
    pub recovered: MetricDelta,
    pub recovery_rate: MetricDelta,
    pub active_jobs: MetricDelta,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DashboardMetrics {
    pub window_days: u32,
    pub generated_at: String,
    pub revenue_at_risk_paise: i64,
    pub recovered_paise: i64,
    pub recovery_rate: f64,
    pub active_jobs: i64,
    pub deltas: MetricDeltas,
    pub funnel: RecoveryFunnel,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TrendPoint {
    /// ISO date, day granularity.
    pub date: String,
    pub at_risk_paise: i64,
    pub recovered_paise: i64,
    pub recovery_rate: f64,
    pub attempts: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FailureBreakdown {
    pub reason: FailureReason,
    pub job_count: i64,
    pub at_risk_paise: i64,
    pub recovered_paise: i64,
    pub recovery_rate: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MethodBreakdown {
    pub method: PaymentMethod,
    pub job_count: i64,
    pub at_risk_paise: i64,
    pub recovered_paise: i64,
    pub recovery_rate: f64,
}

/// How effective each successive retry is, used to cap retry budgets.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AttemptEffectiveness {
    pub attempt: i64,
    pub attempted: i64,
    pub recovered: i64,
    pub recovery_rate: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SuggestedAction {
    pub kind: RecoveryActionKind,
    pub label: String,
    /// Jobs the action would apply to.
    pub job_ids: Vec<String>,
}

/// A finding produced by the recovery engine, not by a person. Always carries
/// its evidence so a merchant can disagree with it.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Insight {
    pub id: String,
    pub kind: InsightKind,
    pub headline: String,
    pub body: String,
    /// Rupees this finding is worth if acted on.
    pub impact_paise: i64,
    pub confidence: f64,
    pub evidence: Vec<Signal>,
    pub suggested_action: Option<SuggestedAction>,
    pub detected_at: String,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PlaybookStep {
    pub sequence: i64,
    pub kind: RecoveryActionKind,
    pub delay_minutes: i64,
    /// Skip this step when the previous one already recovered the money.
    pub stop_on_success: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PlaybookTrigger {
    pub reasons: Vec<FailureReason>,
    pub methods: Vec<PaymentMethod>,
    pub min_amount_paise: Option<i64>,
    pub subscription_only: bool,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PlaybookStats {
    pub jobs_matched: i64,
    pub recovered_paise: i64,
    pub recovery_rate: f64,
}

/// A merchant-editable rule set. The engine only ever runs enabled playbooks.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Playbook {
    pub id: String,
    pub name: String,
    pub description: String,
    pub enabled: bool,
    pub trigger: PlaybookTrigger,
    pub steps: Vec<PlaybookStep>,
    pub stats: PlaybookStats,
    pub updated_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Actor {
    #[serde(rename = "type")]
    pub kind: ActorType,
    pub name: String,
}

impl Actor {
    pub fn engine() -> Self {
        Actor {
            kind: ActorType::Engine,
            name: "recovery-engine".to_string(),
        }
    }

    pub fn scheduler() -> Self {
        Actor {
            kind: ActorType::System,
            name: "scheduler".to_string(),
        }
    }

    pub fn operator(name: impl Into<String>) -> Self {
        Actor {
            kind: ActorType::User,
            name: name.into(),
        }
    }
}

/// Append-only. Every state change in the system lands here.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AuditEvent {
    pub id: String,
    pub at: String,
    pub actor: Actor,
    /// Dotted machine action, e.g. `job.retry.scheduled`.
    pub action: String,
    /// Human sentence for the same thing.
    pub summary: String,
    pub severity: AuditSeverity,
    pub job_id: Option<String>,
    /// Flat key/value context. `BTreeMap` so the UI renders it in a stable
    /// order rather than whatever the hash seed decided this run.
    pub metadata: BTreeMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Merchant {
    pub id: String,
    pub name: String,
    pub mode: MerchantMode,
}

/// Health of the Rust recovery engine, polled by the sidebar.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EngineStatus {
    pub running: bool,
    pub source: EngineSource,
    pub queue_depth: i64,
    pub last_sweep_at: Option<String>,
    /// Razorpay credentials present and accepted.
    pub razorpay_connected: bool,
}

// ---------------------------------------------------------------------------
// Requests from the UI
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QueueFilters {
    #[serde(default)]
    pub statuses: Vec<RecoveryStatus>,
    #[serde(default)]
    pub reasons: Vec<FailureReason>,
    #[serde(default)]
    pub methods: Vec<PaymentMethod>,
    #[serde(default)]
    pub risk_tiers: Vec<RiskTier>,
    /// Matches customer name, email, payment id or order id.
    #[serde(default)]
    pub search: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PageRequest {
    pub offset: i64,
    pub limit: i64,
    #[serde(default)]
    pub sort: Option<JobSort>,
}

impl PageRequest {
    /// Clamped so a malformed request cannot ask for the whole table at once.
    pub fn limit(&self) -> i64 {
        self.limit.clamp(1, 500)
    }

    pub fn offset(&self) -> i64 {
        self.offset.max(0)
    }

    pub fn sort(&self) -> JobSort {
        self.sort.unwrap_or_default()
    }
}

/// Mirrors `AuditQuery extends PageRequest` on the TypeScript side. The fields
/// are spelled out rather than flattened so the shape is obvious from here.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AuditQuery {
    pub offset: i64,
    pub limit: i64,
    #[serde(default)]
    pub severities: Vec<AuditSeverity>,
    #[serde(default)]
    pub search: String,
    #[serde(default)]
    pub job_id: Option<String>,
}

impl AuditQuery {
    pub fn limit(&self) -> i64 {
        self.limit.clamp(1, 1_000)
    }

    pub fn offset(&self) -> i64 {
        self.offset.max(0)
    }
}

/// A page of rows plus the true total, so footers can say "26–50 of 312".
#[derive(Debug, Clone, Serialize)]
pub struct Paged<T> {
    pub rows: Vec<T>,
    pub total: i64,
}

impl<T> Paged<T> {
    pub fn new(rows: Vec<T>, total: i64) -> Self {
        Paged { rows, total }
    }

    pub fn empty() -> Self {
        Paged {
            rows: Vec::new(),
            total: 0,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn enum_json_matches_the_typescript_union() {
        assert_eq!(
            serde_json::to_string(&RecoveryStatus::AwaitingCustomer).unwrap(),
            "\"awaiting_customer\""
        );
        assert_eq!(serde_json::to_string(&Channel::InApp).unwrap(), "\"in_app\"");
        assert_eq!(
            serde_json::to_string(&EngineSource::RustEngine).unwrap(),
            "\"rust-engine\""
        );
    }

    #[test]
    fn enum_storage_name_equals_wire_name() {
        // The whole point of `str_enum!`: one literal drives both.
        for status in RecoveryStatus::ALL {
            let json = serde_json::to_string(status).unwrap();
            assert_eq!(json, format!("\"{}\"", status.as_str()));
            assert_eq!(status.as_str().parse::<RecoveryStatus>().unwrap(), *status);
        }
    }

    #[test]
    fn unknown_enum_values_are_rejected_loudly() {
        assert!("in_flight".parse::<RecoveryStatus>().is_err());
    }

    #[test]
    fn every_status_maps_to_a_funnel_stage() {
        // A status with no stage would silently drop money from the dashboard.
        for status in RecoveryStatus::ALL {
            let stage = status.funnel_stage();
            assert!(FunnelStage::ALL.contains(&stage));
        }
    }

    #[test]
    fn active_statuses_are_never_closed() {
        for status in RecoveryStatus::ACTIVE {
            assert!(!status.is_closed(), "{status} is both active and closed");
        }
    }

    #[test]
    fn camel_case_requests_deserialize() {
        let filters: QueueFilters = serde_json::from_str(
            r#"{"statuses":["queued"],"reasons":[],"methods":["upi"],"riskTiers":["high"],"search":"aarav"}"#,
        )
        .unwrap();
        assert_eq!(filters.statuses, vec![RecoveryStatus::Queued]);
        assert_eq!(filters.methods, vec![PaymentMethod::Upi]);
        assert_eq!(filters.risk_tiers, vec![RiskTier::High]);

        // `sort` is optional on the TypeScript side.
        let page: PageRequest = serde_json::from_str(r#"{"offset":0,"limit":25}"#).unwrap();
        assert_eq!(page.sort(), JobSort::Recent);

        let sorted: PageRequest =
            serde_json::from_str(r#"{"offset":50,"limit":25,"sort":"amount_desc"}"#).unwrap();
        assert_eq!(sorted.sort(), JobSort::AmountDesc);
    }

    #[test]
    fn page_bounds_are_clamped() {
        let hostile: PageRequest =
            serde_json::from_str(r#"{"offset":-40,"limit":9999999}"#).unwrap();
        assert_eq!(hostile.offset(), 0);
        assert_eq!(hostile.limit(), 500);
    }

    #[test]
    fn optional_fields_serialize_as_null_not_missing() {
        // The React types say `string | null`, so the key has to be present.
        let job_id: Option<String> = None;
        let event = AuditEvent {
            id: "evt_1".into(),
            at: "2026-08-22T00:00:00Z".into(),
            actor: Actor::engine(),
            action: "engine.sweep.completed".into(),
            summary: "Queue sweep processed 0 jobs".into(),
            severity: AuditSeverity::Info,
            job_id,
            metadata: BTreeMap::new(),
        };
        let json = serde_json::to_string(&event).unwrap();
        assert!(json.contains("\"jobId\":null"), "{json}");
        assert!(json.contains("\"type\":\"engine\""), "{json}");
    }
}
